# Docker Compose file for defining the services (i.e. containers) in the Bucket list app. We define a service for the api/app code and another for the postgres DB.
services:
  buckets-api:
    build:
      context: .
    env_file: .env
    depends_on:
      - postgres-db
    networks:
      - default
    ports:
      - 8080:8080

  postgres-db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
