# Docker Compose file for defining the services (i.e. containers) in the Bucket list app. We define a service for the api/app code and another for the postgres DB.
services:
  buckets-api:
    build:
      context: .
    env_file: .env
    depends_on:
      - postgres-db
    networks:
      - default
    ports:
      - 8080:8080

  postgres-db:
    image: postgres # TODO: Set the network "buckets_default" for the db service so that the api service can connect to the db service as they have to be on the same network to connect.
    env_file:
      - .env # NB: Do not create an environment variable for a separate user. Instead use the image's default user, postgres and provide enviroment variables for the DB name and password.
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
